In [29]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df=pd.read_csv('/kaggle/input/stroke-prediction-dataset/healthcare-dataset-stroke-data.csv')
df

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [31]:
df.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [32]:
df.duplicated().sum()

0

In [33]:
df.dropna(axis=0,inplace=True)
df.isna().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [34]:
df.drop(columns='id',inplace=True)

In [35]:
df = df.rename(columns={'ever_married': 'Married'})

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4909 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4909 non-null   object 
 1   age                4909 non-null   float64
 2   hypertension       4909 non-null   int64  
 3   heart_disease      4909 non-null   int64  
 4   Married            4909 non-null   object 
 5   work_type          4909 non-null   object 
 6   Residence_type     4909 non-null   object 
 7   avg_glucose_level  4909 non-null   float64
 8   bmi                4909 non-null   float64
 9   smoking_status     4909 non-null   object 
 10  stroke             4909 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 460.2+ KB


In [37]:
df.describe()

age  hypertension  heart_disease  avg_glucose_level  \
count  4909.000000   4909.000000    4909.000000        4909.000000   
mean     42.865374      0.091872       0.049501         105.305150   
std      22.555115      0.288875       0.216934          44.424341   
min       0.080000      0.000000       0.000000          55.120000   
25%      25.000000      0.000000       0.000000          77.070000   
50%      44.000000      0.000000       0.000000          91.680000   
75%      60.000000      0.000000       0.000000         113.570000   
max      82.000000      1.000000       1.000000         271.740000   

               bmi       stroke  
count  4909.000000  4909.000000  
mean     28.893237     0.042575  
std       7.854067     0.201917  
min      10.300000     0.000000  
25%      23.500000     0.000000  
50%      28.100000     0.000000  
75%      33.100000     0.000000  
max      97.600000     1.000000

In [38]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
le=LabelEncoder()

In [39]:
df.age=df.age.astype('int64')
df.avg_glucose_level=df['avg_glucose_level'].astype('int64')
df.bmi=df['bmi'].astype('int64')
df["gender"]=le.fit_transform(df["gender"])
df["Married"]=le.fit_transform(df["Married"])
df["work_type"]=le.fit_transform(df["work_type"])
df["Residence_type"]=le.fit_transform(df["Residence_type"])
df["smoking_status"]=le.fit_transform(df["smoking_status"])

In [40]:
df

gender  age  hypertension  heart_disease  Married  work_type  \
0          1   67             0              1        1          2   
2          1   80             0              1        1          2   
3          0   49             0              0        1          2   
4          0   79             1              0        1          3   
5          1   81             0              0        1          2   
...      ...  ...           ...            ...      ...        ...   
5104       0   13             0              0        0          4   
5106       0   81             0              0        1          3   
5107       0   35             0              0        1          3   
5108       1   51             0              0        1          2   
5109       0   44             0              0        1          0   

      Residence_type  avg_glucose_level  bmi  smoking_status  stroke  
0                  1                228   36               1       1  
2                  0                105   32               2       1  
3                  1                171   34               3       1  
4                  0                174   24               2       1  
5                  1                186   29               1       1  
...              ...                ...  ...             ...     ...  
5104               0                103   18               0       0  
5106               1                125   40               2       0  
5107               0                 82   30               2       0  
5108               0                166   25               1       0  
5109               1                 85   26               0       0  

[4909 rows x 11 columns]

In [41]:
x = df.drop(columns=['stroke','avg_glucose_level', 'heart_disease'])
y = df.stroke
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [42]:
x

gender  age  hypertension  Married  work_type  Residence_type  bmi  \
0          1   67             0        1          2               1   36   
2          1   80             0        1          2               0   32   
3          0   49             0        1          2               1   34   
4          0   79             1        1          3               0   24   
5          1   81             0        1          2               1   29   
...      ...  ...           ...      ...        ...             ...  ...   
5104       0   13             0        0          4               0   18   
5106       0   81             0        1          3               1   40   
5107       0   35             0        1          3               0   30   
5108       1   51             0        1          2               0   25   
5109       0   44             0        1          0               1   26   

      smoking_status  
0                  1  
2                  2  
3                  3  
4                  2  
5                  1  
...              ...  
5104               0  
5106               2  
5107               2  
5108               1  
5109               0  

[4909 rows x 8 columns]

In [43]:
model_svm = SVC(kernel = 'sigmoid', random_state = 0)
model_svm.fit(X_train, y_train)

SVC(kernel='sigmoid', random_state=0)

In [44]:
y_pred = model_svm.predict(X_test)

In [45]:
accuracy_svm = accuracy_score(y_test, y_pred)
print('Accuracy:',accuracy_svm)

Accuracy: 0.9660556687033266


In [46]:
classification_rep_svm = classification_report(y_test, y_pred)
print(classification_rep_svm)

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1423
           1       0.00      0.00      0.00        50

    accuracy                           0.97      1473
   macro avg       0.48      0.50      0.49      1473
weighted avg       0.93      0.97      0.95      1473



/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [47]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC
import pandas as pd


y_pred = model_svm.predict(X_test)

results = np.column_stack((X_test, y_test, y_pred))

# Display the results
print("Test Data with Predictions:")
print(results)

# Generate classification report
classification_rep_svm = classification_report(y_test, y_pred)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print classification report
print("\nClassification Report:")
print(classification_rep_svm)

# Print confusion matrix
print("\nConfusion Matrix:")
print(conf_matrix)


Test Data with Predictions:
[[ 1 51  0 ...  2  0  0]
 [ 1 52  0 ...  3  0  0]
 [ 0 35  0 ...  2  0  0]
 ...
 [ 0  3  0 ...  0  0  0]
 [ 0 20  0 ...  2  0  0]
 [ 0  1  0 ...  0  0  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1423
           1       0.00      0.00      0.00        50

    accuracy                           0.97      1473
   macro avg       0.48      0.50      0.49      1473
weighted avg       0.93      0.97      0.95      1473


Confusion Matrix:
[[1423    0]
 [  50    0]]


/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
